### PR TITLE
Enable unit tests and Roborazzi screenshot tests in feature/rustlayout

### LINKED ISSUE #484: Restore Screenshot comparisons in RustLayout feature branch

### PR DESCRIPTION
**Pull request by timothyfroehlich**
Create tasks to build the Rust libraries for the developer's host, configure the test tasks to use it

Three PR's in one, but it's simplest to have them together to have tests working.

The first is the CargoPlugin changes that splits the CargoBuildTask into Android and Host subclasses and registers tasks to build the libraries for the host.

The second is the changes to the build.gradle.kts files which add dependencies on the host build tasks and adds the libraries to the `java.library.path` for the tests. This is very hacky and brittle and I've mostly figured out how to do it properly, but it was taking too long and I want to get screenshot tests working. I have #502 to do this properly.

The last is getting the screenshot tests working, both updating the serialized files and setting the tests to expect failure, so that the tasks that generate and compare screenshots still succeed. 

There won't be any screenshot diff comments in this PR, because the comment workflow compares the screenshots generated from this PR against those generated by the base branch, feature/rustlayout, which isn't yet generating screenshots! But once this is merged into to feature/rustlayout, the tracking PR for merging it into to main, #461, will update with the screenshot comparison vs main. I put up #503 to make sure the screenshot diffs were working too.

Fixes #484

### CODE REVIEW

**Comment by timothyfroehlich** [comment]
@rylin, can you take a look at this soon?

**Comment by timothyfroehlich** [comment]
@rylin, can you take a look at this soon?

**Comment by timothyfroehlich** [comment]
@rylin, can you take a look at this soon?

**Comment by timothyfroehlich** [comment]
@rylin, can you take a look at this soon?

**Comment by rylin8** [comment]
> @rylin, can you take a look at this soon?

I took a look and it doesn't seem to break anything, but I honestly don't understand most of the changes. Will approve but you might want to have someone else take a look.

**Review by rylin8 — APPROVED** [review]

**Comment by timothyfroehlich** [comment]
> > @rylin, can you take a look at this soon?
> 
> I took a look and it doesn't seem to break anything, but I honestly don't understand most of the changes. Will approve but you might want to have someone else take a look.

I will for sure once I do the non-hacky version. But for now I want to get the screenshot tests working on this branch.

**Comment by iamralpht** [comment]
+1 to get screenshot testing going. I think I see something odd in the
masking test, actually — before is definitely broken, but there might be
some issues in the after, too (missing second rainbow?)?

**Comment by rylin8** [comment]
The after for masking is correct. I fixed a bug with masking in the layout branch where it didn't support densities other than 1. The second rainbow should not be visible. It was a test that initially made for multiple masks under the same parent, which we decided we wouldn't support yet.

**Pull request merged**
