### PR TITLE
Read dcf file from res/raw

### PR DESCRIPTION
**Pull request by dipenpradhan**
Set rawResourceId using DesignSettings
Load file from res/raw/the_design_file when set
This allows Runtime Resource Overlays to target the resource

### CODE REVIEW

**Review by Gurupreet — APPROVED** [review]

**Comment by timothyfroehlich** [comment]
Dipen, would you be able to add a test for this? A unit test should be fine. You can add it alongside `designcompose/src/testDebug/kotlin/com/android/designcompose/DesignSwitcherBasicTests.kt` and use the HelloWorld DCF

**Review by iamralpht — APPROVED** [review]
Changes LGTM, but as @timothyfroehlich says, please add a test.

**Review by timothyfroehlich — CHANGES_REQUESTED** [review]
Oh, and to clean up the formatting, the easiest thing to do is to run ./dev-tools/format-all.sh

**Comment by dipenpradhan** [comment]
> Oh, and to clean up the formatting, the easiest thing to do is to run ./dev-tools/format-all.sh

Done


> Dipen, would you be able to add a test for this? A unit test should be fine. You can add it alongside `designcompose/src/testDebug/kotlin/com/android/designcompose/DesignSwitcherBasicTests.kt` and use the HelloWorld DCF

Done,  added `DesignRawResourceTest`

**Comment by dipenpradhan** [comment]
Added `DocServer#testOnlyClearDocuments` and `DocServer#testOnlyClearFileFetchStatus()` for clearing state

**Review by timothyfroehlich — CHANGES_REQUESTED** [review]
Almost there, but we need to get the test doc added to dev-scripts/update_dcfs.sh

**Comment by dipenpradhan** [comment]
Closing this PR and moving to main repo:https://github.com/google/automotive-design-compose/pull/1778

**Pull request closed without merging**
