### PR TITLE
Fix Dependabot config

### PR DESCRIPTION
**Pull request by timothyfroehlich**

### CODE REVIEW

**Comment by rylin8** [comment]
Are you able to force the dependabot check to run?

**Comment by timothyfroehlich** [comment]
> Are you able to force the dependabot check to run?

I don't think so, why do you ask?

**Comment by rylin8** [comment]
> 

To see if it fixes the problem

**Comment by timothyfroehlich** [comment]
> > 
> 
> To see if it fixes the problem

Oh, I think we're good. Turns out I did have a linter running in VSCode and it was pointing out problems, but I missed it. It's not reporting any problems any more.

**Review by rylin8 — APPROVED** [review]

**Pull request merged**
