### PR TITLE
Disable CodeQL, we haven't been using it and it's been failing

### PR DESCRIPTION
**Pull request by timothyfroehlich**

### CODE REVIEW

**Comment by iamralpht** [comment]
Not reviewing because this is in conflict, but let me know if you need a +1.

**Comment by timothyfroehlich** [comment]
Rebased, it's good to go now.

**Comment by timothyfroehlich** [comment]
Will get CodeQL working again sometime down the line.

**Review by iamralpht — APPROVED** [review]
Yep, good to come back to this, but not urgent now.

**Pull request merged**
