### PR TITLE
Update MediaCompose to latest Unbundled release, reintegrate into the main Gradle Project

### PR DESCRIPTION
**Pull request by timothyfroehlich**
The `ub-automotive-master-20231102` Unbundled release includes changes that allow the Unbundled libraries to be built into a local maven repository. This allows the MediaCompose apps to use those built libraries separately from the Unbundled Gradle project. MediaCompose has been updated to use this release.

MediaCompose has also been reintegrated into the main DesignCompose Gradle project. Because it requires the Unbundled libraries it will only be included if the `unbundledAAOSDir` gradle property is set. It will check to make sure that the unbundled libraries have been built before proceeding with a build.

New setup instructions:
- Update your Unbundled checkout to the latest release, 20231102:

```bash
cd $YOUR_UNBUNDLED_REPO_PATH
repo init -u https://android.googlesource.com/platform/manifest -b ub-automotive-master-20231102
repo sync -cq -j8
```

- Build the Unbundled libraries:

```bash
cd $YOUR_UNBUNDLED_REPO_PATH/packages/apps/Car/libs/aaos-apps-gradle-project
./gradlew publishAllPublicationsToLocalRepository
```

- Now build MediaCompose from the main Gradle project:

```bash
cd $DESIGNCOMPOSE_CHECKOUT_ROOT
./gradlew mediacompose-app:assembleDebug
```

### CODE REVIEW

**Comment by timothyfroehlich** [comment]
The corresponding change to Unbundled has been merged, now just waiting for the next Unbundled release.

**Comment by timothyfroehlich** [comment]
Blocked until the next Unbundled release

**Comment by timothyfroehlich** [comment]
Unbundled released on Oct 11th, seems like things almost work, but I'm getting a crash on boot with my emulator. Will need to spend some time confirming the code and set-up, making sure there were no regressions.

**Review by iamralpht — APPROVED** [review]

**Comment by iamralpht** [comment]
Really excited to get MediaCompose in CI, and to have it building against latest unbundled!

**Pull request merged**
