### PR TITLE
Fix the non-squoosh renderer not able to close the overlay

### PR DESCRIPTION
**Pull request by yiqunw700**
Also fixes crashes where removeLast() can not be found on device api level 33.

Fixes: #1712

### CODE REVIEW

**Comment by yiqunw700** [comment]
I couldn't figure out how to fix the sizing of the overlay. Filed #1717 ticket to look into that afterwards.

**Comment by timothyfroehlich** [comment]
It works for me! But I think Ralph should approve.

**Comment by iamralpht** [comment]
I thought of one other thing to test - in the navigation tests, there's an overlay that appears from the bottom which has buttons behind it. It's worth testing that when the overlay is visible, you can't click through it to the buttons behind.

(I think this regression must have come from a Compose update, so it's also worth adding a regression test for this case)

**Comment by timothyfroehlich** [comment]
> I thought of one other thing to test - in the navigation tests, there's an overlay that appears from the bottom which has buttons behind it.

There is? I'm not seeing it on my emulator, with or without squoosh.

**Comment by timothyfroehlich** [comment]
> I thought of one other thing to test - in the navigation tests, there's an overlay that appears from the bottom which has buttons behind it. It's worth testing that when the overlay is visible, you can't click through it to the buttons behind.
> 
> (I think this regression must have come from a Compose update, so it's also worth adding a regression test for this case)

@iamralpht I added navigation tests to #1711, do those look like they catch what you're looking for?

**Comment by yiqunw700** [comment]
> I thought of one other thing to test - in the navigation tests, there's an overlay that appears from the bottom which has buttons behind it. It's worth testing that when the overlay is visible, you can't click through it to the buttons behind.

In the overlay positioning test, when overlay shows up, I am not able to click on any buttons(nothing happens) outside of the overlay content.
In the overlay navigation test, when overlay shows up, clicking outside of the overlay content(anywhere including the buttons behind) dismisses the overlay because figma sets the CLOSE_ON_CLICK_OUTSIDE set to be true.

**Comment by iamralpht** [comment]
Yeah, I think the updated tests cover the scenario. Thanks for making the improvements!

**Review by iamralpht — APPROVED** [review]

**Pull request merged**
