### PR TITLE
Update serialized files for Validation and HelloWorld

### PR DESCRIPTION
**Pull request by timothyfroehlich**
The test-all script will be able to run all of the emulator tests again.

### CODE REVIEW

**Comment by rylin8** [comment]
Was this all done manually?

**Comment by timothyfroehlich** [comment]
Yes.

**Comment by rylin8** [comment]
I wonder why the Battleship doc got so much smaller? Can you verify that it still works?

**Comment by rylin8** [comment]
I have an pull request that ups the version again -- any recommendations on how to quickly update all these files again manually before the plugin you're working on is done? https://github.com/google/automotive-design-compose/pull/228/files#diff-3c5d32a8188320d75917eaed6fc4ef91a3909ffb4f7cce6271d1f1c7950775a0

**Comment by timothyfroehlich** [comment]
No, not yet, just open validation and click through them one by one, then grab them all from Android Studio's Device Explorer.

**Comment by timothyfroehlich** [comment]
> 

Yep, it opens up just fine. Not sure why it's smaller.

**Review by rylin8 — APPROVED** [review]

**Pull request merged**
