### PR TITLE
Add support to read dcf file from res/raw

### PR DESCRIPTION
**Pull request by dipenpradhan**
Add support in DesignSettings and DocServer to use R.raw.* Add unit test for loading HelloWorld dcf file from res/raw Add test methods in DesignSettings and DocServer
Add more steps to clear state in ClearStateTestRule

Test: ./gradlew designcompose:testDebugUnitTest# Please enter the commit message for your changes.
         ./dev-scripts/update_dcfs.sh

### CODE REVIEW

**Comment by dipenpradhan** [comment]
Closed https://github.com/google/automotive-design-compose/pull/1761 because of presubmit failures due to forking.

Contents of PR are same

**Review by timothyfroehlich — CHANGES_REQUESTED** [review]
Let me know when you've addressed the comments I left in the original

**Comment by dipenpradhan** [comment]
> Let me know when you've addressed the comments I left in the original

Comments:
> We're not taking any screenshots in this test, so we can remove this rule

Removed unused `testName` and `roborazziRule`

> Let's rename this file to be more clear, something like RawResourceTestDoc.dcf?

Renamed to `raw_resource_test_hello_world_doc`, because in res/raw: `File-based resource names must contain only lowercase a-z, 0-9, or underscore`

> We need to get the test doc added to dev-scripts/update_dcfs.sh

Added a step in `common-functions.sh` to copy hello world doc to `designcompose/testDebug/res/raw`

**Review by timothyfroehlich — APPROVED** [review]
LGTM!

**Pull request merged**
